version: '3.9'
services:
  db:
    image: postgres:13.3
    container_name: db
    env_file:
      - .env-dev
  app:
    build:
      context: .
    env_file:
      - .env-dev
    container_name: app
    command: ["/app/scripts/run.sh"]
    ports:
      - "8000:8000"
    depends_on:
      - db
