"""Splitting the table into two

Revision ID: 344e5f15bfb3
Revises: 608e49235fbe
Create Date: 2024-04-18 22:34:08.136108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '344e5f15bfb3'
down_revision: Union[str, None] = '608e49235fbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('short_url',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=False),
    sa.Column('number_of_transitions', sa.Integer(), nullable=True),
    sa.Column('short_url', sa.String(), nullable=False),
    sa.Column('qr_code', sa.String(), nullable=False),
    sa.Column('is_activ', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['url.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('number_of_transitions', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('original_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('short_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('qr_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_activ', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='tokens_pkey')
    )
    op.drop_table('short_url')
    op.drop_table('url')
    # ### end Alembic commands ###
