"""empty message

Revision ID: 608e49235fbe
Revises: 
Create Date: 2024-03-29 22:49:30.158499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '608e49235fbe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('number_of_transitions', sa.Integer(), nullable=True),
                    sa.Column('original_url', sa.String(), nullable=False),
                    sa.Column('short_url', sa.String(), nullable=False),
                    sa.Column('qr_code', sa.String(), nullable=False),
                    sa.Column('is_activ', sa.Boolean(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    # ### end Alembic commands ###
