"""add three words

Revision ID: 6520baa059d5
Revises: b218e02c0edd
Create Date: 2024-06-24 16:29:49.281997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6520baa059d5'
down_revision: Union[str, None] = 'b218e02c0edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_url', sa.Column('three_words', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('short_url', 'three_words')
    # ### end Alembic commands ###
