"""update

Revision ID: 71c449848d98
Revises: 344e5f15bfb3
Create Date: 2024-04-18 23:05:01.989209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71c449848d98'
down_revision: Union[str, None] = '344e5f15bfb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_url', sa.Column('url_id', sa.Integer(), nullable=False))
    op.drop_constraint('short_url_parent_id_fkey', 'short_url', type_='foreignkey')
    op.create_foreign_key(None, 'short_url', 'url', ['url_id'], ['id'])
    op.drop_column('short_url', 'parent_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('short_url', sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'short_url', type_='foreignkey')
    op.create_foreign_key('short_url_parent_id_fkey', 'short_url', 'url', ['parent_id'], ['id'])
    op.drop_column('short_url', 'url_id')
    # ### end Alembic commands ###
